EthereumCommonwealth/etherwallet

- app/scripts/controllers/walletBalanceCtrl.js
- app/scripts/directives/balanceDrtv.html
- app/scripts/main.js
- Add WalletService to Wallet Balance Controller
- Add watcher to retrieve the balance of 4 currencies: ETH, ETC, UBQ, EXP
- Show in the template the each currency's balance except the currency picked in the Node's dropdown. 
Proof of the feature
> Multi balance

- app/scripts/controllers/sendTxCtrl.js
- app/scripts/controllers/tabsCtrl.js
- app/scripts/controllers/walletBalanceCtrl.js
- app/scripts/ens.js
- app/scripts/main.js
- yarn.lock
- Fix UBQ/EXP transactions 
- Change network from URL querystring
> Fix UBQ/EXP transactions and Change network from URL querystring

- app/styles/etherwallet-custom.less
> Fix header's css

- app/includes/header.tpl
- app/scripts/controllers/footerCtrl.js
- app/scripts/controllers/tabsCtrl.js
Step: 0.1 GWEI
Min: 0.1 GWEI
Max: 60 GWEI
> Minimum gas price 0.1 GWEI

- app/scripts/controllers/bulkGenCtrl.js
- app/scripts/controllers/ensCtrl.js
- app/scripts/controllers/sendTxCtrl.js
- app/scripts/controllers/tabsCtrl.js
- app/scripts/controllers/walletGenCtrl.js
> Remove multiples alerts when use network parameter

- app/scripts/tokens/ethTokens.json
Hi,
I'm proposing to add PETRO token as a token in CEW.
https://etherscan.io/token/0xec18f898b4076a3e18f1089d33376cc380bde61d
> Add Petro token

- app/scripts/nodes.js
**New:**
- RPC Server for Callisto Testnet
RPC URL: https://testnet.callisto.network
**Proof of feature:**
> Add CLO testnet

- app/includes/header.tpl
- app/scripts/controllers/footerCtrl.js
- app/scripts/controllers/tabsCtrl.js
Callisto needs a minimum gas price of 1800 Gwei, right now CEW just supported up to 60 Gwei.
With this change, CEW can support from 1800 Gwei up to 3600 Gwei if the blockchain picked is Callisto.
Known issue: The `range input` works poorly when changing from ing/ETC <> Callisto.
> Correct gas price for Callisto

- app/scripts/nodes.js
> Add UBIQ RPC node

- app/includes/header.tpl
- app/includes/helpers.tpl
- app/scripts/controllers/CX/myWalletsCtrl.js
- app/scripts/controllers/ensCtrl.js
- app/scripts/controllers/footerCtrl.js
- app/scripts/controllers/tabsCtrl.js
- app/scripts/controllers/walletBalanceCtrl.js
- app/scripts/globalFuncs.js
- app/scripts/main.js
Changes:
- ECNS gas limit set to 570k - Issue https://github.com/EthereumCommonwealth/Roadmap/issues/40
- Gas price UX bug - Issue: https://github.com/EthereumCommonwealth/Roadmap/issues/40
-  1.3 second delay between typing and lookup execution to allow user to type a full name first. - Issue: https://github.com/EthereumCommonwealth/Roadmap/issues/26#issuecomment-342088948
> Gas price improvement

- app/scripts/nodes.js
New:
\* Node is still syncing - blocks 1723776/4909619
Proof:
> Add Ethereum Commonwealth nodes

- app/scripts/uiFuncs.js
fixes: 
Gas autoevaluation bug - https://github.com/EthereumCommonwealth/Roadmap/issues/40
I successfully posted a transaction w/ set gasLimit
https://ropsten.etherscan.io/tx/0x982b5d5a508010af100a1606754d0ffc31b048c13b6306baacac8b03adf8ab3c
> add gas limit

- app/includes/contracts-deploy-1.tpl
- app/scripts/controllers/contractsCtrl.js
issues:
1. tx data unsanitized
1.  gas limit evaluation
changes:
1. manual gas limit eval added  check for constructor params
1. sanitize tx data
> fixes #29 & #31

- app/includes/contracts-deploy-1.tpl
- app/scripts/controllers/contractsCtrl.js
- app/scripts/translations/en.js
1.  notify user if cannot find construtor in ABI
1.  invalidate gas limit field on error and notify user
> notify user:

- app/scripts/nodes.js
> Add Parity RPC node

- app/scripts/nodeHelpers/etherscan.js
- app/scripts/nodes.js
issue: wrong url passed in w/ etherscan nodes
updated:
'this' reference in etherscan node
> fix testnet balance

- app/scripts/uiFuncs.js
issue: remove 'to' field if blank
> fix contract deployment w/ classic mask

- app/includes/contracts-interact-modal.tpl
- app/scripts/controllers/contractsCtrl.js
> estimate gas limit write contract

- app/scripts/controllers/contractsCtrl.js
fixes #53
issues:
1. old tx data in new tx
1. when writing to contract, did not call generateTx
to update params (nonce)
changes:
1. call to generateTx in writeToContract
1. reset rawTx and signedTx fields on interact / deploy switch
> update tx data w/ new tx

- app/scripts/nodes.js
- Remove old CLO testnet
- Remove Mantis node -we need to fix the stuck issue-
- Modify the nodes to 0xinfra.com
> Modify ETC nodes

- app/includes/sendTx-content.tpl
- app/scripts/controllers/tabsCtrl.js
add removed addr field
ensure gasPrice isn't NaN value
> hotfix: gasPrice, addr field

- app/scripts/controllers/contractsCtrl.js
deployed multi sig contract to ropsten network, and checked owners to see if deployed and interacted successfully.
0xD50Fea94Cdf21B0A0f2975E56619F446FeB7C59D
> parse array type

- app/scripts/controllers/messagesCtrl.js
this should fix case for overwriting and saving duplicates
> save index w/ message

- app/scripts/controllers/messagesCtrl.js
object keys are not guaranteed to return in order, since we save index, we can utilize for unique values
> simplify messageSet function

- app/scripts/nodes.js
> Fix leftover settings of ETSC

- app/includes/header.tpl
- app/scripts/controllers/tabsCtrl.js
- app/scripts/globalFuncs.js
- app/scripts/uiFuncs.js
fixes #87 
Note:
Step is set to 0.1
if value has more precision than 1 decimal place, it throws error, although it is in range.
ex: 2.2 works, 2.21 throws error
> Update/gas price check #87

- app/includes/messages-new.tpl
- app/includes/messages.tpl
- app/scripts/controllers/messagesCtrl.js
update:
new message visible w/ addr only
disabled button for send w/ addr only
check for addr only on form submittal
fixes:
1. active class for tabs
1. this should fix time delay for trezor while allowing
viewing capabillity of msg functions w/ addr only.
> change ui for new msg -#86

- app/scripts/nodes.js
- app/styles/etherwallet-custom.less
Node used and maintained by clopool.net (https://clopool.net)
+ HTTPS throught AWS ELB
+ Load Balancing for [Multi-Geth](https://github.com/ethereumsocial/multi-geth) backend (Using 4 multi-geth clustering)
+ Blockchain up to date.
+ Response time ~150-350ms
+ KR servers
+ You can check live status on [clostats.net](https://clostats.net)
> Add CLO node api

- app/scripts/staticJS/trezorConnect.v3.js
- app/scripts/uiFuncs.js
issue: chainId throws error for callisto 820.
change:
1. trezor: remove chainId if callisto. trezor displays unknown (UNKN) coin
to user, sends successful tx
https://explorer.callisto.network/tx/0xa0070fee399e2e4bd56a356f7acd66946a5d25d4653bbe00f341241823172c9e
1. update connect to v4
do the same for other hww
> send callisto w/ hardware wallet.

- app/includes/messages-new.tpl
- app/includes/messages.tpl
- app/scripts/controllers/messagesCtrl.js
issue:
1. form submit error w/ wallet type
1. button still disabled after unlocking w/ hardware wallet
1. wallet.type not updated w/ hardware wallet, reads 'addressOnly'
changed:
1. disable button on hwType which gets correctly updated
1. simplify sendMessage
remove http request for tx data
notify user gas estimation error
> send msg w/ hardware wallet

- app/layouts/cx-wallet.html
- app/scripts/main.js
fix html and imports for chrome extension
> fix ch-ext html

- app/includes/swap-stage-1.tpl
- app/includes/swap-stage-2.tpl
- app/scripts/changeNow.js
- app/scripts/controllers/swapCtrl.js
- app/styles/etherwallet-swap.less
update swap UI 
changes:
estimate conv ratio FE
select coin on form submittal
fix dropdown functionality
mobile friendly stage 2
> Update/swap change now #54

- app/includes/header-node-modal.tpl
- app/scripts/controllers/tabsCtrl.js
fixes #147 
saves node for etc, clo, and eth
adds clo to default values
> Fix/save local node #147

- app/scripts/controllers/CX/addWalletCtrl.js
- app/scripts/controllers/decryptWalletCtrl.js
- app/scripts/directives/walletDecryptDrtv.html
- app/scripts/globalFuncs.js
- app/scripts/nodes.js
- app/styles/etherwallet-custom.less
+ Updated Hardware wallet support for custom networks
+ Updated MUSIC and CLO node settings
**Preview**
> Update custom networks

- app/scripts/translations/ko.js
See also https://github.com/kvhnuke/etherwallet/pull/1875
> more korean translation, added missing strings

- app/includes/sendTx-content.tpl
issue:
wallet balance fetched async, and hasEnoughBalance() defaults to false if loading.
changes:
remove alert
not terribly important and did not want to change
hasEnoughBalance function to default to true if loading and since it's used in other controllers.
> remove not enough balance error

- app/scripts/ajaxReq.js
- app/scripts/controllers/CX/addWalletCtrl.js
- app/scripts/controllers/CX/myWalletsCtrl.js
- app/scripts/controllers/txStatusCtrl.js
- app/scripts/directives/transactionCost.html
- app/scripts/directives/transactionCostDtrv.js
- app/scripts/myetherwallet.js
- app/scripts/nodeHelpers/coinPrice.js
- app/scripts/services/globalService.js
**changes:**
1. store coinPrices in memory to avoid multiple http requests
1. add help icon
1. edit input text
handled error response.
Getting error fetching CLO price (working last week)
Hide component if no prices
> handle error from coin price

- app/layouts/helpers.html
issue:
helper page broken
changes:
added in controllers to match index.html layout
todo:
fix tabsCtrl to link back to index or remove
> fix helper html

- app/includes/cold-staking-withdraw-modal.tpl
- app/scripts/controllers/coldStakingCtrl.js
- app/scripts/controllers/walletBalanceCtrl.js
- app/scripts/directives/balanceDrtv.html
- app/scripts/ethFuncs.js
- app/scripts/services/coldStakingService.js
- app/scripts/uiFuncs.js
- app/styles/etherwallet-custom.less
issue:
sent tx obj into uiFuncs.sendTx defaults to web3 sending
changes:
send signedTx instead
> fix start staking call

- app/scripts/myetherwallet.js
issue:
wallet balance error on some networks 
changes:
only set balance on successful response
> only set wallet balance on successful response

- app/scripts/directives/balanceDrtv.html
- app/styles/etherwallet-custom.less
> Fix/button disabled #169

- app/includes/cold-staking-claimReward-modal.tpl
- app/includes/cold-staking-startStaking-modal.tpl
- app/includes/cold-staking-withdraw-modal.tpl
- app/scripts/services/coldStakingService.js
disable buttons
cast staking threshold to ether 
add fallback values for modals
> Update/cold staking #171

- app/includes/cold-staking-claimReward-modal.tpl
- app/includes/cold-staking-startStaking-modal.tpl
- app/includes/cold-staking-withdraw-modal.tpl
issue:
checked userCanWithdraw on page load,
and if on wrong network, throws error
> only call contract info on network

- app/includes/viewWalletInfo-content.tpl
- app/includes/viewWalletInfo.tpl
issue:
ng-show called getPrivateKeyString() even if wallet.type !== default
changes:
replace ng-show w/ ng-if
> remove call for priv key w/ web3 wallet in 'view wallet info' tab

- app/scripts/nodes.js
- app/styles/etherwallet-custom.less
Chainkorea is closing ETC RPC node service since no one is using 😂 ,
> [Network] Remove obsolete networks

- app/scripts/nodes.js
+ Update ETH endpoint and POA node endpoint from upstream
> [Network] Update nodes from upstream

- app/scripts/directives/addressFieldDrtv.js
- app/scripts/directives/balanceDrtv.html
- app/scripts/main.js
- app/scripts/web3Wallet.js
issues:
remove addrField unused services
remove dup addrField
> fix imports

- app/includes/header.tpl
- app/scripts/controllers/decryptWalletCtrl.js
- app/scripts/controllers/tabsCtrl.js
- app/scripts/main.js
- app/scripts/services/globalService.js
issues:
1. network not set when connecting to web3 wallet
1. dropdownNode doesn't toggle 
changes:
change network when connecting to web3 wallet
move dropdownNode variable to service so UI can update
> close dropdown on node selection

- app/scripts/controllers/sendTxCtrl.js
- app/scripts/controllers/tabsCtrl.js
- app/scripts/directives/customNodeForm.html
**issues:**
1. calling removeNodeFromLocal() not removing node due to network stored as 'options' instead of type
1. duplicate id in html
**changes:**
1. update reference to localNode.type from localNode.options
1. change element id
> Fix/removeNodeFromLocal() & 2 elements w/ same id

- app/scripts/directives/accountBalanceTable.html
- app/scripts/directives/coinIcon.html
- app/scripts/directives/coinIcon.js
- app/scripts/directives/networkSelector.html
- app/styles/bootstrap/dropdowns.less
- app/styles/etherwallet-variables.less
changes:
1. Coin icons should be placed at the left side of the dropdown menu
1. Network ticker names should be written in default gray text
1. The name of the network which is currently selected should be written in light-green text
1. change coin symbol text color in account balance table
> update node selector

- app/scripts/controllers/swapCtrl.js
- app/scripts/directives/tokenBalances.html
- app/scripts/directives/transactionCost.js
- app/scripts/main.js
- app/scripts/myetherwallet.js
changes:
fix reference to node.type -> ajaxRex.type
pass timeout sidebar
html error coin icon sidebar
remove unused api calls swap
**issues:**
> fix node.type ref / html / $timeout

- app/includes/footer.tpl
- app/includes/header.tpl
changes:
move css selector to footer
https gastracker link for donation
remove "ClassicEtherWallet.com" and "ethereumproject.github.io/etherwallet/" button-links
> move css theme selector to footer

- app/includes/cold-staking-claimReward-modal.tpl
- app/includes/cold-staking-startStaking-modal.tpl
- app/includes/cold-staking-withdraw-modal.tpl
- app/scripts/contract.js
- app/scripts/controllers/coldStakingCtrl.js
- app/scripts/controllers/walletBalanceCtrl.js
- app/scripts/directives/accountBalanceTable.html
- app/scripts/directives/accountBalanceTable.js
- app/scripts/ethFuncs.js
- app/scripts/main.js
- app/scripts/services/coinPrice.service.js
- app/scripts/services/coldStaking.service.js
- app/styles/bootstrap/progress-bars.less
- app/styles/etherwallet-custom.less
- app/styles/etherwallet-master.less
- app/styles/etherwallet-variables.less
- package.json
- yarn.lock
add cold staking UI
**changes:**
1. call to staker() for info
1. call withdraw() to withdraw
1. fix babel polyfill n 11+
**issues:**:
staker() time is fetches current time, not staking time
> cold staking UI / babel polyfill fix
